/**
 * NEX_REELS Royalty-Free Audio & Trending Sounds Library
 * Curated 20 trending funks, phonk, synthwave, trap, and lo-fi beats
 * 
 * COPYRIGHT NOTICE:
 * To avoid DMCA strikes and app-store bans, all tracks provided here are 100% royalty-free
 * for commercial & social use under Creative Commons / Jamendo / Pixabay / FreeMusicArchive licenses.
 * 
 * SCALING EXTENSION POINT:
 * When scaling NEXCHAT to millions of users, replace or augment this local pool with:
 * 1. Spotify Web API (Track metadata & 30s preview streams): https://developer.spotify.com/documentation/web-api
 * 2. TikTok Commercial Music Library (TCML API): https://ads.tiktok.com/marketing_api/docs?id=1738740523091970
 * 3. Audius Web3 Music Streaming API: https://docs.audius.org/
 */

export const TRENDING_SOUNDS = [
  {
    id: 'sound-1',
    title: 'Cyberpunk Drift Phonk',
    artist: 'DEMON_BEATS',
    genre: 'Brazilian Phonk',
    duration: '0:45',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=phonk-drift-112199.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-2',
    title: 'Neon Tokyo Funk 2088',
    artist: 'Future_Wave',
    genre: 'Funk / Cyberwave',
    duration: '0:38',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=future-bass-108728.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-3',
    title: 'Midnight City Glide',
    artist: 'K-Trap Labs',
    genre: 'Drill Trap',
    duration: '0:50',
    url: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=trap-future-122757.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-4',
    title: 'Quantum Lo-Fi Chill',
    artist: 'NEX_Records',
    genre: 'Lo-Fi Chill',
    duration: '0:55',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=lofi-study-112191.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-5',
    title: 'Hyperdrive Synthwave',
    artist: 'Retro_Future',
    genre: 'Synthwave',
    duration: '0:42',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/24/audio_3d1a89c4d8.mp3?filename=synthwave-80s-110045.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-6',
    title: 'Dark Brazilian Funk',
    artist: 'Favela_Sound',
    genre: 'Funk / Phonk',
    duration: '0:35',
    url: 'https://cdn.pixabay.com/download/audio/2023/04/10/audio_5174542289.mp3?filename=phonk-dark-145638.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-7',
    title: 'Electric Cyber Bloom',
    artist: 'Astra_Bass',
    genre: 'EDM / Dance',
    duration: '0:48',
    url: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_03d6d531ef.mp3?filename=electronic-future-beats-125023.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-8',
    title: 'Glitch Horizon',
    artist: 'Hex_Core',
    genre: 'Glitch Hop',
    duration: '0:40',
    url: 'https://cdn.pixabay.com/download/audio/2021/08/09/audio_88424c1045.mp3?filename=glitch-hop-beat-9014.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-9',
    title: 'Matrix Awakening',
    artist: 'Zero_One',
    genre: 'Cyber Ambient',
    duration: '0:52',
    url: 'https://cdn.pixabay.com/download/audio/2022/02/07/audio_d0a13f69d2.mp3?filename=chill-abstract-intention-12099.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-10',
    title: 'Shadow Runner Drill',
    artist: 'Ghost_808',
    genre: 'UK Drill',
    duration: '0:44',
    url: 'https://cdn.pixabay.com/download/audio/2023/02/28/audio_550519fbb2.mp3?filename=trap-beat-shadow-140228.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-11',
    title: 'Sunset Boulevard Beat',
    artist: 'Coast_Groove',
    genre: 'Boom Bap',
    duration: '0:36',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=boom-bap-hip-hop-111425.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-12',
    title: 'Neon Tokyo Fast Life',
    artist: 'Shibuya_Drift',
    genre: 'Speed Phonk',
    duration: '0:33',
    url: 'https://cdn.pixabay.com/download/audio/2023/08/01/audio_145b23d9fa.mp3?filename=fast-phonk-rage-160100.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-13',
    title: 'Chrono Pulse',
    artist: 'NEX_Synth',
    genre: 'Deep House',
    duration: '0:46',
    url: 'https://cdn.pixabay.com/download/audio/2022/08/02/audio_884b238dc2.mp3?filename=deep-club-house-117584.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-14',
    title: 'After Hours Funk',
    artist: 'Late_Night_Lab',
    genre: 'Nu-Disco',
    duration: '0:50',
    url: 'https://cdn.pixabay.com/download/audio/2022/04/27/audio_03d6d531ef.mp3?filename=funk-disco-groove-111003.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-15',
    title: 'Ghost Protocol Trap',
    artist: 'Cipher_Ghost',
    genre: 'Hard Trap',
    duration: '0:41',
    url: 'https://cdn.pixabay.com/download/audio/2022/12/22/audio_1808fbf07a.mp3?filename=hard-trap-808-131456.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-16',
    title: 'Cosmic Rain Piano',
    artist: 'Starlight_Keys',
    genre: 'Emotional Lo-Fi',
    duration: '0:58',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_c8c8a73467.mp3?filename=piano-rain-chill-108722.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-17',
    title: 'Velocity Surge',
    artist: 'Apex_Nitro',
    genre: 'Drum & Bass',
    duration: '0:39',
    url: 'https://cdn.pixabay.com/download/audio/2023/06/15/audio_3d1a89c4d8.mp3?filename=dnb-liquid-rush-153400.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-18',
    title: 'Vaporwave Memories',
    artist: 'Mall_1995',
    genre: 'Vaporwave',
    duration: '0:53',
    url: 'https://cdn.pixabay.com/download/audio/2022/02/10/audio_5174542289.mp3?filename=vaporwave-aesthetic-105020.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-19',
    title: 'Cyber Samurai Trap',
    artist: 'Katana_Drop',
    genre: 'Asian Trap / Phonk',
    duration: '0:42',
    url: 'https://cdn.pixabay.com/download/audio/2023/03/12/audio_03d6d531ef.mp3?filename=samurai-trap-koto-142100.mp3',
    cover: 'logo.jpg',
  },
  {
    id: 'sound-20',
    title: 'Quantum Ascension',
    artist: 'NEX_Orchestra',
    genre: 'Epic Cinematic',
    duration: '1:02',
    url: 'https://cdn.pixabay.com/download/audio/2022/06/20/audio_db6591201e.mp3?filename=epic-cinematic-trailer-113200.mp3',
    cover: 'logo.jpg',
  },
];
